# Generated by Django 3.1.1 on 2020-11-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_queue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='user',
            new_name='user_a',
        ),
        migrations.RenameField(
            model_name='queueposition',
            old_name='queue',
            new_name='queue_a',
        ),
        migrations.RenameField(
            model_name='queueposition',
            old_name='user',
            new_name='user_a',
        ),
    ]
