# Generated by Django 3.1.1 on 2020-11-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_queue', '0002_auto_20201117_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='user_a',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='queueposition',
            old_name='queue_a',
            new_name='queue',
        ),
        migrations.RenameField(
            model_name='queueposition',
            old_name='user_a',
            new_name='user',
        ),
    ]
