# Generated by Django 3.1.1 on 2020-11-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_queue', '0005_queueposition_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='img',
            field=models.ImageField(default='0', upload_to='queues/'),
        ),
    ]
